version: '3.8'

services:

# Front

  rush00_front:
    container_name: rush00
    #depends_on:
    #  - rush00_back
    build:
      context: ./front
    restart: always
    ports:
      - 4200:4200

# Back
  db:
    image: postgres:15
    restart: always
    volumes:
      - "./db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
