name: Lint Code Base

on:
  pull_request:
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cd into front
        run: cd front

      - name: Restore dependencies
        run: npm install
        
      - name: Npm run lint
        run: npm run lint